create table med.job_titles (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text,
    CONSTRAINT pk_job_titles PRIMARY KEY (id)
);

create table med.doctors (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    last_name text not null,
    first_name text not null,
    middle_name text,
    job_title_id integer,
    date_employed date,
    uni_name text,
    uni_specialty text,
    CONSTRAINT pk_doctors PRIMARY KEY (id),
    CONSTRAINT fk_doctors_jobtitles_jobtitle_id FOREIGN KEY (job_title_id) REFERENCES med.job_titles (id)
);

create table med.clinics (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    chief_doctor_id integer,
    full_name text not null,
    short_name varchar(50),
    address text,
    email varchar(320),
    CONSTRAINT pk_clinics PRIMARY KEY (id),
    CONSTRAINT fk_clinics_doctors_chief_id FOREIGN KEY (chief_doctor_id) REFERENCES med.doctors (id)
);

create table med.doctor_clinics (
    doctor_id integer not null,
    clinic_id integer not null,
    CONSTRAINT pk_doctorclinics PRIMARY KEY (doctor_id, clinic_id),
    CONSTRAINT fk_doctorclinics_doctors_docid FOREIGN KEY (doctor_id) REFERENCES med.doctors (id),
    CONSTRAINT fk_doctorclinics_clinics_clncid FOREIGN KEY (clinic_id) REFERENCES med.clinics (id)
);

create table med.patients (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    last_name text not null,
    first_name text not null,
    middle_name text,
    passport_num varchar(10) not null,
    dob date,
    gender char(1) not null,
    phone text,
    CONSTRAINT pk_patients PRIMARY KEY (id)
);

create table med.patient_visits (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    patient_id integer not null,
    doctor_id integer not null,
    clinic_id integer not null,
    visit_date timestamp,
    complaints text,
    exam text,
    recommend text,
    CONSTRAINT pk_patient_visits PRIMARY KEY (id),
    CONSTRAINT fk_patientvisits_patients_patid FOREIGN KEY (patient_id) REFERENCES med.patients (id),
    CONSTRAINT fk_patientvisits_docclinics_docid_clncid foreign key (doctor_id, clinic_id) references med.doctor_clinics (doctor_id, clinic_id)
);

create table med.diagnoses (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code varchar(20),
    name text,
    CONSTRAINT pk_diagnoses PRIMARY KEY (id)
);

create table med.patient_visit_diag (
    visit_id integer not null,
    diag_id integer not null,
    CONSTRAINT pk_patvisdiag PRIMARY KEY (visit_id, diag_id),
    CONSTRAINT fk_patvisdiag_patvis_visitid FOREIGN KEY (visit_id) REFERENCES med.patient_visits (id),
    CONSTRAINT fk_patvisdiag_diag_diagid FOREIGN KEY (diag_id) REFERENCES med.diagnoses (id)
);
